name: Continuous Integration
on:
  workflow_dispatch: null
  push:
    branches:
      - main
  pull_request: null

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 'stable', 'oldstable' ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Vet
        run: make vet
      - name: Lint
        run: make lint
      - name: Helm Lint
        run: make helm-lint
      - name: Test
        run: make test
      - name: Build
        run: make build
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            linode/linode-cloud-controller-manager
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{raw}},value=${{ github.ref_name }}
      - name: Build Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REV=${{ github.ref_name }}
